### ISSUE TITLE
Handle server restarts

### ISSUE THREAD

**Issue by lukhas** [michael1241/mongotopy#5]
When the server is being restarted, or is briefly down between the "shutting down" and the "up" status, mongotopy crashes with the following error:

```
Aug 01 07:31:27 boole mongotopy.py[6424]: Traceback (most recent call last):
Aug 01 07:31:27 boole mongotopy.py[6424]:   File "/home/mongotopy/mongotopy.py", line 33, in <module>
Aug 01 07:31:27 boole mongotopy.py[6424]:     saveMongoData()
Aug 01 07:31:27 boole mongotopy.py[6424]:   File "/home/mongotopy/mongotopy.py", line 25, in saveMongoData
Aug 01 07:31:27 boole mongotopy.py[6424]:     mongodata = reformat(json.loads(stdout.decode("utf-8")))
Aug 01 07:31:27 boole mongotopy.py[6424]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Aug 01 07:31:27 boole mongotopy.py[6424]:     return _default_decoder.decode(s)
Aug 01 07:31:27 boole mongotopy.py[6424]:   File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
Aug 01 07:31:27 boole mongotopy.py[6424]:     raise JSONDecodeError("Extra data", s, end)
Aug 01 07:31:27 boole mongotopy.py[6424]: json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
Aug 01 07:31:27 boole systemd[1]: mongotopy.service: Main process exited, code=exited, status=1/FAILURE
Aug 01 07:31:27 boole systemd[1]: mongotopy.service: Failed with result 'exit-code'.
```

It would be nicer if mogotopy just complained in the logs (on stderr) about this and kept trying.

**Comment by michael1241** [comment]
I think https://github.com/michael1241/mongotopy/commit/e9867673f50df85b6c4417b65f8ea7eaccd3c1cb should fix it, not sure how to test but it shouldn't break any worse...

**Comment by michael1241** [comment]
Actually will spam logs, will add a sleep.

**Comment by michael1241** [comment]
Ok https://github.com/michael1241/mongotopy/commit/3e03ec28918d8d7e475ea45cb6b8549a0257fbfe should be fixed now.

**Comment by lukhas** [comment]
Deployed, cheers.
