### ISSUE TITLE
Mongotopy crashing during a mongodb maintenance

### ISSUE THREAD

**Issue by lukhas** [michael1241/mongotopy#6]
We upgraded our primary this morning and I mongotopy tried gathering stats right as the server was restarting and it failed:

```
Nov 16 07:10:19 archi mongotopy.py[14159]: Traceback (most recent call last):
Nov 16 07:10:19 archi mongotopy.py[14159]:   File "/home/mongotopy/mongotopy.py", line 36, in <module>
Nov 16 07:10:19 archi mongotopy.py[14159]:     saveMongoData()
Nov 16 07:10:19 archi mongotopy.py[14159]:   File "/home/mongotopy/mongotopy.py", line 27, in saveMongoData
Nov 16 07:10:19 archi mongotopy.py[14159]:     mongodata = reformat(json.loads(stdout.decode("utf-8")))
Nov 16 07:10:19 archi mongotopy.py[14159]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Nov 16 07:10:19 archi mongotopy.py[14159]:     return _default_decoder.decode(s)
Nov 16 07:10:19 archi mongotopy.py[14159]:   File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
Nov 16 07:10:19 archi mongotopy.py[14159]:     raise JSONDecodeError("Extra data", s, end)
Nov 16 07:10:19 archi mongotopy.py[14159]: json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
Nov 16 07:10:19 archi mongotopy.py[14159]: During handling of the above exception, another exception occurred:
Nov 16 07:10:19 archi mongotopy.py[14159]: Traceback (most recent call last):
Nov 16 07:10:19 archi mongotopy.py[14159]:   File "/home/mongotopy/mongotopy.py", line 38, in <module>
Nov 16 07:10:19 archi mongotopy.py[14159]:     sys.stderr.write(e)
Nov 16 07:10:19 archi mongotopy.py[14159]: TypeError: write() argument must be str, not JSONDecodeError
Nov 16 07:10:19 archi systemd[1]: mongotopy.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 07:10:19 archi systemd[1]: mongotopy.service: Failed with result 'exit-code'.
```

It would be nice if this failure was handled smoothly (ie. log errors in stdout but do not crash and keep retrying).

**Comment by michael1241** [comment]
Should be fixed now (have not tested but I consulted a higher power).

**Comment by lukhas** [comment]
Oh it was crashing while printing the reason why it would have crashed, that's funny.

Deployed, thanks!
